[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Series"
  pageRef = "series"
  weight = 40

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

