colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
logo = "img/logo.png"
disableTextInHeader = false
defaultBackgroundImage = "img/header_image.jpg"
highlightCurrentMenuArea = true
smartTOC = true

# Existing Disqus threads; see layouts/partials/comments.html
disqusShortname = "nyan101-github-io"

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/header_image.jpg"
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/blog/posts/"
  cardView = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showAuthor = true
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showCategories = true
  showTags = true
  showWordCount = false
  showComments = true
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[term]
  showTableOfContents = false
  groupByYear = true
